package matcher

var KnownAppNames = map[string]bool{
	"safari":                  true,
	"terminal":                true,
	"finder":                  true,
	"mail":                    true,
	"messages":                true,
	"notes":                   true,
	"calendar":                true,
	"contacts":                true,
	"reminders":               true,
	"photos":                  true,
	"music":                   true,
	"tv":                      true,
	"books":                   true,
	"maps":                    true,
	"facetime":                true,
	"preview":                 true,
	"textedit":                true,
	"calculator":              true,
	"chess":                   true,
	"activity monitor":        true,
	"disk utility":            true,
	"console":                 true,
	"system settings":         true,
	"screenshot":              true,
	"image capture":           true,
	"stickies":                true,
	"time machine":            true,
	"automator":               true,
	"font book":               true,
	"siri":                    true,
	"shortcuts":               true,
	"home":                    true,
	"clock":                   true,
	"weather":                 true,
	"stocks":                  true,
	"news":                    true,
	"tips":                    true,
	"photo booth":             true,
	"voice memos":             true,
	"freeform":                true,
	"journal":                 true,
	"passwords":               true,
	"image playground":        true,
	"iphone mirroring":        true,
	"iina":                    true,
	"arc":                     true,
	"iterm":                   true,
	"iterm2":                  true,
	"jdownloader2":            true,
	"obs":                     true,
	"localsend":               true,
	"orbstack":                true,
	"ollama":                  true,
	"lm studio":               true,
	"jan":                     true,
	"raycast":                 true,
	"zoom.us":                 true,
	"surfshark":               true,
	"bitwarden":               true,
	"brave browser":           true,
	"google chrome":           true,
	"pixelmator pro":          true,
	"capture one 22":          true,
	"davinci resolve":         true,
	"karabiner-elements":      true,
	"keyclu":                  true,
	"mailspring":              true,
	"microsoft word":          true,
	"microsoft excel":         true,
	"microsoft powerpoint":    true,
	"microsoft defender":      true,
	"google drive":            true,
	"google docs":             true,
	"google sheets":           true,
	"google slides":           true,
	"whatsapp":                true,
	"tidal":                   true,
	"calibre":                 true,
	"balenaetcher":            true,
	"pasty":                   true,
	"runcat":                  true,
	"appcleaner":              true,
	"zerotier":                true,
	"omnidisksweeper":         true,
	"onyx":                    true,
	"vnc viewer":              true,
	"windows app":             true,
	"microsoft remote desktop": true,
	"loops":                   true,
	"openswarm":               true,
	"remio":                   true,
	"adobe acrobat reader":    true,
	"adobe":                   true,
	"adobe creative cloud":    true,
	"notion":                  true,
	"msty":                    true,
	"firefox":                 true,
	"spotify":                 true,
	"visual studio code":      true,
	"code":                    true,
	"vscode":                  true,
}

func IsKnownApp(name string) bool {
	return KnownAppNames[name]
}
